experiment/feat/next-13/4

diff --git a/.docker/Dockerfile.dev b/.docker/Dockerfile.dev
--- a/.docker/Dockerfile.dev
+++ b/.docker/Dockerfile.dev
@@ -19,7 +19,14 @@ ARG ROOT_PASS
 ARG USERNAME
 ARG GROUP
 ARG REPO_REL_PATH
-ARG PROJECT_ROOT='/utkusarioglu-com/projects/nextjs-grpc'
+ARG PROJECT_ROOT
+
+RUN for arg in ROOT_PASS USERNAME GROUP REPO_REL_PATH PROJECT_ROOT; do \
+  if [ -z "${!arg}" ]; then \
+    echo "Error: arg $arg is required for the docker build operation" \
+    exit 1 \
+  fi \
+done
 
 WORKDIR  $PROJECT_ROOT/$REPO_REL_PATH
 COPY $REPO_REL_PATH $PROJECT_ROOT/$REPO_REL_PATH
